//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(identifier: "ruanhao.test.XLWB") ?? Bundle.main
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `MainVCSettings.json`.
    static let mainVCSettingsJson = Rswift.FileResource(bundle: R.hostingBundle, name: "MainVCSettings", pathExtension: "json")
    
    /// `bundle.url(forResource: "MainVCSettings", withExtension: "json")`
    static func mainVCSettingsJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.mainVCSettingsJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 57 images.
  struct image {
    /// Image `LaunchImage`.
    static let launchImage = Rswift.ImageResource(bundle: R.hostingBundle, name: "LaunchImage")
    /// Image `ad_background`.
    static let ad_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "ad_background")
    /// Image `avatar_default_big`.
    static let avatar_default_big = Rswift.ImageResource(bundle: R.hostingBundle, name: "avatar_default_big")
    /// Image `common_button_white_disable`.
    static let common_button_white_disable = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_button_white_disable")
    /// Image `navigationbar_arrow_down`.
    static let navigationbar_arrow_down = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_arrow_down")
    /// Image `navigationbar_arrow_up`.
    static let navigationbar_arrow_up = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_arrow_up")
    /// Image `navigationbar_friendattention_highlighted`.
    static let navigationbar_friendattention_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_friendattention_highlighted")
    /// Image `navigationbar_friendattention`.
    static let navigationbar_friendattention = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_friendattention")
    /// Image `navigationbar_pop_highlighted`.
    static let navigationbar_pop_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_pop_highlighted")
    /// Image `navigationbar_pop`.
    static let navigationbar_pop = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_pop")
    /// Image `new_feature_1`.
    static let new_feature_1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_1")
    /// Image `new_feature_2`.
    static let new_feature_2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_2")
    /// Image `new_feature_3`.
    static let new_feature_3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_3")
    /// Image `new_feature_4`.
    static let new_feature_4 = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_4")
    /// Image `new_feature_button_highlighted`.
    static let new_feature_button_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_button_highlighted")
    /// Image `new_feature_button`.
    static let new_feature_button = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_button")
    /// Image `new_feature_finish_button_highlighted`.
    static let new_feature_finish_button_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_finish_button_highlighted")
    /// Image `new_feature_finish_button`.
    static let new_feature_finish_button = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_finish_button")
    /// Image `new_feature_share_false`.
    static let new_feature_share_false = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_share_false")
    /// Image `new_feature_share_true`.
    static let new_feature_share_true = Rswift.ImageResource(bundle: R.hostingBundle, name: "new_feature_share_true")
    /// Image `popover_background_left`.
    static let popover_background_left = Rswift.ImageResource(bundle: R.hostingBundle, name: "popover_background_left")
    /// Image `popover_background_right`.
    static let popover_background_right = Rswift.ImageResource(bundle: R.hostingBundle, name: "popover_background_right")
    /// Image `popover_background`.
    static let popover_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "popover_background")
    /// Image `preview_like_icon_disable`.
    static let preview_like_icon_disable = Rswift.ImageResource(bundle: R.hostingBundle, name: "preview_like_icon_disable")
    /// Image `preview_like_icon_highlighted`.
    static let preview_like_icon_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "preview_like_icon_highlighted")
    /// Image `preview_like_icon`.
    static let preview_like_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "preview_like_icon")
    /// Image `qrcode_border`.
    static let qrcode_border = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_border")
    /// Image `qrcode_button_background`.
    static let qrcode_button_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_button_background")
    /// Image `qrcode_embeddedimage_shadow`.
    static let qrcode_embeddedimage_shadow = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_embeddedimage_shadow")
    /// Image `qrcode_navigationbar_background`.
    static let qrcode_navigationbar_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_navigationbar_background")
    /// Image `qrcode_scanline_barcode`.
    static let qrcode_scanline_barcode = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_scanline_barcode")
    /// Image `qrcode_scanline_qrcode`.
    static let qrcode_scanline_qrcode = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_scanline_qrcode")
    /// Image `qrcode_tabbar_background`.
    static let qrcode_tabbar_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_background")
    /// Image `qrcode_tabbar_icon_barcode_highlighted`.
    static let qrcode_tabbar_icon_barcode_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_icon_barcode_highlighted")
    /// Image `qrcode_tabbar_icon_barcode`.
    static let qrcode_tabbar_icon_barcode = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_icon_barcode")
    /// Image `qrcode_tabbar_icon_qrcode_highlighted`.
    static let qrcode_tabbar_icon_qrcode_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_icon_qrcode_highlighted")
    /// Image `qrcode_tabbar_icon_qrcode`.
    static let qrcode_tabbar_icon_qrcode = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_icon_qrcode")
    /// Image `qrcode_tip_background`.
    static let qrcode_tip_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tip_background")
    /// Image `tabbar_background`.
    static let tabbar_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_background")
    /// Image `tabbar_compose_button_highlighted`.
    static let tabbar_compose_button_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_compose_button_highlighted")
    /// Image `tabbar_compose_button`.
    static let tabbar_compose_button = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_compose_button")
    /// Image `tabbar_compose_icon_add_highlighted`.
    static let tabbar_compose_icon_add_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_compose_icon_add_highlighted")
    /// Image `tabbar_compose_icon_add`.
    static let tabbar_compose_icon_add = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_compose_icon_add")
    /// Image `tabbar_discover_highlighted`.
    static let tabbar_discover_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_discover_highlighted")
    /// Image `tabbar_discover`.
    static let tabbar_discover = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_discover")
    /// Image `tabbar_home_highlighted`.
    static let tabbar_home_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_home_highlighted")
    /// Image `tabbar_home`.
    static let tabbar_home = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_home")
    /// Image `tabbar_message_center_highlighted`.
    static let tabbar_message_center_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_message_center_highlighted")
    /// Image `tabbar_message_center`.
    static let tabbar_message_center = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_message_center")
    /// Image `tabbar_profile_highlighted`.
    static let tabbar_profile_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_profile_highlighted")
    /// Image `tabbar_profile`.
    static let tabbar_profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_profile")
    /// Image `visitordiscover_feed_image_house`.
    static let visitordiscover_feed_image_house = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_feed_image_house")
    /// Image `visitordiscover_feed_image_smallicon`.
    static let visitordiscover_feed_image_smallicon = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_feed_image_smallicon")
    /// Image `visitordiscover_feed_mask_smallicon`.
    static let visitordiscover_feed_mask_smallicon = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_feed_mask_smallicon")
    /// Image `visitordiscover_image_message`.
    static let visitordiscover_image_message = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_image_message")
    /// Image `visitordiscover_image_profile`.
    static let visitordiscover_image_profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_image_profile")
    /// Image `visitordiscover_signup_logo`.
    static let visitordiscover_signup_logo = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_signup_logo")
    
    /// `UIImage(named: "LaunchImage", bundle: ..., traitCollection: ...)`
    static func launchImage(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launchImage, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ad_background", bundle: ..., traitCollection: ...)`
    static func ad_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ad_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "avatar_default_big", bundle: ..., traitCollection: ...)`
    static func avatar_default_big(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.avatar_default_big, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_button_white_disable", bundle: ..., traitCollection: ...)`
    static func common_button_white_disable(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_button_white_disable, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_arrow_down", bundle: ..., traitCollection: ...)`
    static func navigationbar_arrow_down(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_arrow_down, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_arrow_up", bundle: ..., traitCollection: ...)`
    static func navigationbar_arrow_up(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_arrow_up, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_friendattention", bundle: ..., traitCollection: ...)`
    static func navigationbar_friendattention(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_friendattention, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_friendattention_highlighted", bundle: ..., traitCollection: ...)`
    static func navigationbar_friendattention_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_friendattention_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_pop", bundle: ..., traitCollection: ...)`
    static func navigationbar_pop(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_pop, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_pop_highlighted", bundle: ..., traitCollection: ...)`
    static func navigationbar_pop_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_pop_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_1", bundle: ..., traitCollection: ...)`
    static func new_feature_1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_1, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_2", bundle: ..., traitCollection: ...)`
    static func new_feature_2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_3", bundle: ..., traitCollection: ...)`
    static func new_feature_3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_3, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_4", bundle: ..., traitCollection: ...)`
    static func new_feature_4(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_4, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_button", bundle: ..., traitCollection: ...)`
    static func new_feature_button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_button, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_button_highlighted", bundle: ..., traitCollection: ...)`
    static func new_feature_button_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_button_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_finish_button", bundle: ..., traitCollection: ...)`
    static func new_feature_finish_button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_finish_button, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_finish_button_highlighted", bundle: ..., traitCollection: ...)`
    static func new_feature_finish_button_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_finish_button_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_share_false", bundle: ..., traitCollection: ...)`
    static func new_feature_share_false(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_share_false, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_share_true", bundle: ..., traitCollection: ...)`
    static func new_feature_share_true(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.new_feature_share_true, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "popover_background", bundle: ..., traitCollection: ...)`
    static func popover_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.popover_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "popover_background_left", bundle: ..., traitCollection: ...)`
    static func popover_background_left(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.popover_background_left, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "popover_background_right", bundle: ..., traitCollection: ...)`
    static func popover_background_right(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.popover_background_right, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "preview_like_icon", bundle: ..., traitCollection: ...)`
    static func preview_like_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.preview_like_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "preview_like_icon_disable", bundle: ..., traitCollection: ...)`
    static func preview_like_icon_disable(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.preview_like_icon_disable, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "preview_like_icon_highlighted", bundle: ..., traitCollection: ...)`
    static func preview_like_icon_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.preview_like_icon_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_border", bundle: ..., traitCollection: ...)`
    static func qrcode_border(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_border, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_button_background", bundle: ..., traitCollection: ...)`
    static func qrcode_button_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_button_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_embeddedimage_shadow", bundle: ..., traitCollection: ...)`
    static func qrcode_embeddedimage_shadow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_embeddedimage_shadow, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_navigationbar_background", bundle: ..., traitCollection: ...)`
    static func qrcode_navigationbar_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_navigationbar_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_scanline_barcode", bundle: ..., traitCollection: ...)`
    static func qrcode_scanline_barcode(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_scanline_barcode, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_scanline_qrcode", bundle: ..., traitCollection: ...)`
    static func qrcode_scanline_qrcode(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_scanline_qrcode, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_background", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_barcode", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_barcode(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_icon_barcode, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_barcode_highlighted", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_barcode_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_icon_barcode_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_qrcode", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_qrcode(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_icon_qrcode, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_qrcode_highlighted", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_qrcode_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_icon_qrcode_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tip_background", bundle: ..., traitCollection: ...)`
    static func qrcode_tip_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tip_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_background", bundle: ..., traitCollection: ...)`
    static func tabbar_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_button", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_compose_button, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_button_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_button_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_compose_button_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_icon_add", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_icon_add(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_compose_icon_add, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_icon_add_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_icon_add_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_compose_icon_add_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_discover", bundle: ..., traitCollection: ...)`
    static func tabbar_discover(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_discover, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_discover_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_discover_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_discover_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_home", bundle: ..., traitCollection: ...)`
    static func tabbar_home(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_home, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_home_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_home_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_home_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_message_center", bundle: ..., traitCollection: ...)`
    static func tabbar_message_center(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_message_center, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_message_center_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_message_center_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_message_center_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_profile", bundle: ..., traitCollection: ...)`
    static func tabbar_profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_profile, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_profile_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_profile_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_profile_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_feed_image_house", bundle: ..., traitCollection: ...)`
    static func visitordiscover_feed_image_house(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_feed_image_house, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_feed_image_smallicon", bundle: ..., traitCollection: ...)`
    static func visitordiscover_feed_image_smallicon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_feed_image_smallicon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_feed_mask_smallicon", bundle: ..., traitCollection: ...)`
    static func visitordiscover_feed_mask_smallicon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_feed_mask_smallicon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_image_message", bundle: ..., traitCollection: ...)`
    static func visitordiscover_image_message(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_image_message, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_image_profile", bundle: ..., traitCollection: ...)`
    static func visitordiscover_image_profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_image_profile, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_signup_logo", bundle: ..., traitCollection: ...)`
    static func visitordiscover_signup_logo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_signup_logo, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `visitorView`.
    static let visitorView = _R.nib._visitorView()
    
    /// `UINib(name: "visitorView", in: bundle)`
    static func visitorView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.visitorView)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `newfeatureCell`.
    static let newfeatureCell: Rswift.ReuseIdentifier<NewFeatureCell> = Rswift.ReuseIdentifier(identifier: "newfeatureCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 11 storyboards.
  struct storyboard {
    /// Storyboard `Discover`.
    static let discover = _R.storyboard.discover()
    /// Storyboard `Home`.
    static let home = _R.storyboard.home()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `Me`.
    static let me = _R.storyboard.me()
    /// Storyboard `Message`.
    static let message = _R.storyboard.message()
    /// Storyboard `NewFeatureViewController`.
    static let newFeatureViewController = _R.storyboard.newFeatureViewController()
    /// Storyboard `Null`.
    static let null = _R.storyboard.null()
    /// Storyboard `Popover`.
    static let popover = _R.storyboard.popover()
    /// Storyboard `QRcodeViewController`.
    static let qRcodeViewController = _R.storyboard.qRcodeViewController()
    /// Storyboard `WelcomeViewController`.
    static let welcomeViewController = _R.storyboard.welcomeViewController()
    /// Storyboard `oAuthViewController`.
    static let oAuthViewController = _R.storyboard.oAuthViewController()
    
    /// `UIStoryboard(name: "Discover", bundle: ...)`
    static func discover(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.discover)
    }
    
    /// `UIStoryboard(name: "Home", bundle: ...)`
    static func home(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.home)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "Me", bundle: ...)`
    static func me(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.me)
    }
    
    /// `UIStoryboard(name: "Message", bundle: ...)`
    static func message(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.message)
    }
    
    /// `UIStoryboard(name: "NewFeatureViewController", bundle: ...)`
    static func newFeatureViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.newFeatureViewController)
    }
    
    /// `UIStoryboard(name: "Null", bundle: ...)`
    static func null(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.null)
    }
    
    /// `UIStoryboard(name: "Popover", bundle: ...)`
    static func popover(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.popover)
    }
    
    /// `UIStoryboard(name: "QRcodeViewController", bundle: ...)`
    static func qRcodeViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.qRcodeViewController)
    }
    
    /// `UIStoryboard(name: "WelcomeViewController", bundle: ...)`
    static func welcomeViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.welcomeViewController)
    }
    
    /// `UIStoryboard(name: "oAuthViewController", bundle: ...)`
    static func oAuthViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.oAuthViewController)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _visitorView.validate()
    }
    
    struct _visitorView: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "visitorView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> visitorView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? visitorView
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "common_button_white_disable") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common_button_white_disable' is used in nib 'visitorView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "visitordiscover_feed_mask_smallicon") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'visitordiscover_feed_mask_smallicon' is used in nib 'visitorView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "visitordiscover_feed_image_smallicon") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'visitordiscover_feed_image_smallicon' is used in nib 'visitorView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "visitordiscover_feed_image_house") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'visitordiscover_feed_image_house' is used in nib 'visitorView', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try discover.validate()
      try welcomeViewController.validate()
      try qRcodeViewController.validate()
      try me.validate()
      try home.validate()
      try popover.validate()
      try message.validate()
    }
    
    struct discover: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Discover"
      
      static func validate() throws {
        if UIKit.UIImage(named: "tabbar_discover") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_discover' is used in storyboard 'Discover', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct home: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Home"
      
      static func validate() throws {
        if UIKit.UIImage(named: "tabbar_home") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_home' is used in storyboard 'Home', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = MainViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    struct me: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Me"
      
      static func validate() throws {
        if UIKit.UIImage(named: "tabbar_profile") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_profile' is used in storyboard 'Me', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct message: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Message"
      
      static func validate() throws {
        if UIKit.UIImage(named: "tabbar_message_center") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_message_center' is used in storyboard 'Message', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct newFeatureViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = NewFeatureViewController
      
      let bundle = R.hostingBundle
      let name = "NewFeatureViewController"
      
      fileprivate init() {}
    }
    
    struct null: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = NullViewController
      
      let bundle = R.hostingBundle
      let name = "Null"
      
      fileprivate init() {}
    }
    
    struct oAuthViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = oAuthViewController
      
      let bundle = R.hostingBundle
      let name = "oAuthViewController"
      
      fileprivate init() {}
    }
    
    struct popover: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "Popover"
      
      static func validate() throws {
        if UIKit.UIImage(named: "popover_background") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'popover_background' is used in storyboard 'Popover', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct qRcodeViewController: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "QRcodeViewController"
      
      static func validate() throws {
        if UIKit.UIImage(named: "qrcode_tabbar_icon_qrcode") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'qrcode_tabbar_icon_qrcode' is used in storyboard 'QRcodeViewController', but couldn't be loaded.") }
        if UIKit.UIImage(named: "qrcode_border") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'qrcode_border' is used in storyboard 'QRcodeViewController', but couldn't be loaded.") }
        if UIKit.UIImage(named: "qrcode_scanline_qrcode") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'qrcode_scanline_qrcode' is used in storyboard 'QRcodeViewController', but couldn't be loaded.") }
        if UIKit.UIImage(named: "qrcode_tabbar_icon_barcode") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'qrcode_tabbar_icon_barcode' is used in storyboard 'QRcodeViewController', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct welcomeViewController: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = WelcomeViewController
      
      let bundle = R.hostingBundle
      let name = "WelcomeViewController"
      
      static func validate() throws {
        if UIKit.UIImage(named: "ad_background") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ad_background' is used in storyboard 'WelcomeViewController', but couldn't be loaded.") }
        if UIKit.UIImage(named: "avatar_default_big") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'avatar_default_big' is used in storyboard 'WelcomeViewController', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}